### ISSUE TITLE
Dynamic height of list item

### ISSUE THREAD

**Issue by Vasantika20** [logiczsniper/nested_scroll_controller#1]
Can we use Listview with dynamic heights of item? And also can we get first visible item & scroll particular item to top position?

**Comment by logiczsniper** [comment]
I am not sure... Any chance you could post the widget that you are trying to use a nested scroll controller with? When I get the time I can give it a go!

**Comment by Vasantika20** [comment]
I want to implement UI like in uber eats app, you can check the video [UberEatsApp](https://youtu.be/LrOR5QOCHBI)
For this i need scroll to position when tab changed & first visible item to sync tab bar with the list. i hope you understand.

**Comment by logiczsniper** [comment]
Thank you for your patience!

> scroll to position

By position do you mean an offset or an index? Apologies if this is not what you meant, but if you want to jump to the same offset in the new tab (on tab change), I would recommend you try adding a listener to the controller and keep track of the current total offset. On tab change, scroll to that offset with `nestedScrollController.nestedJumpTo(offset)`. Let me know how that goes or if I misunderstood!

**Comment by Vasantika20** [comment]
Thank you for your response. Yes you are right, nestedScrollController.nestedJumpTo(offset) will help me to achieve this. but if i have dynamic heights of list item, then how to store offsets of items?

**Comment by logiczsniper** [comment]
Hmm that is a good question, but the `nested_scroll_controller` is not responsible for storing offsets of items! The idea of the package is to complete some of the same functionality of the standard scroll controller - which does not store offsets of items. Sorry I couldnt be of any more help, thank you for reaching out!

**Comment by Vasantika20** [comment]
Ok, Thank you
